version: "5.0"

services:

  server:
    image: backend
    container_name: cloud-storage
    build: ./
    ports:
      - "5050:5050"
    depends_on:
      - database

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/Security
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pgAdmin"

  database:
    image: postgres
    container_name: cloud_db
    volumes:
      - /"db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pgAdmin"
    ports:
      - 3306:3306









